# Generated by Django 3.2.5 on 2022-11-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tarehe_kuzaliwa', models.DateField()),
                ('simu', models.CharField(max_length=200)),
                ('mahali_kuzaliwa', models.CharField(max_length=200)),
                ('jinsia', models.CharField(choices=[('Kiume', 'Kiume'), ('Kike', 'Kike')], max_length=200)),
                ('kumpokea_yesu', models.DateField()),
                ('mahali_anakotoka', models.CharField(help_text='mahali alikompokea yesu', max_length=200)),
                ('dhehebu', models.CharField(max_length=200)),
                ('dhehebu_alilookolea', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('tarehe_ubaatizo', models.DateField()),
                ('mahali_ubatizo', models.CharField(max_length=200)),
                ('maji_mengi', models.BooleanField(default=False)),
                ('trh_kujazwa_roho_mtakatifu', models.DateField()),
                ('mahali_roho_mtakatifu', models.DateField()),
                ('huduma_aliyonayo', models.CharField(max_length=200)),
                ('anatoa_zaka', models.BooleanField(default=False)),
                ('ameajiriwa', models.BooleanField(default=False)),
                ('ameoa_ameolewa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.day')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.department')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('feetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.feetype')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.department')),
                ('sub_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.sub_department')),
            ],
        ),
    ]
