# Generated by Django 3.2.5 on 2023-02-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeType',
            new_name='Offering',
        ),
        migrations.AlterModelOptions(
            name='zaka',
            options={'verbose_name_plural': 'Zaka'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='dhehebu_alilookolea',
            new_name='dhehebu_alikookokea',
        ),
        migrations.AddField(
            model_name='member',
            name='namba_ya_zaka',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='ameajiriwa',
            field=models.CharField(choices=[('Ameajiriwa', 'Ameajiriwa'), ('Amejiajiri', 'Amejiajiri'), ('Hana Kazi', 'Hana Kazi')], max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='ameoa_ameolewa',
            field=models.CharField(choices=[('Ameoa', 'Ameoa'), ('Ameolewa', 'Ameolewa'), ('Hajaolewa', 'Hajaolewa'), ('Hajaoa', 'Hajaoa')], max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='anatoa_zaka',
            field=models.CharField(choices=[('Anatoa Zaka', 'Anatoa Zaka'), ('Hatoi Zaka', 'Hatoi Zaka')], max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='maji_mengi',
            field=models.CharField(choices=[('Maji Mengi', 'Maji Mengi'), ('Maji Kidogo', 'Maji Kidogo')], max_length=200),
        ),
    ]
