# Generated by Django 3.2.5 on 2022-11-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_payment_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mahali_roho_mtakatifu',
            field=models.CharField(default='Geita', max_length=200),
        ),
    ]
