# Generated by Django 3.2.5 on 2022-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_mahali_roho_mtakatifu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
